# Generated by Django 5.1.4 on 2025-08-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
    ]
