# Generated by Django 5.1.4 on 2025-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_categories_products_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
